default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "admin") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "12345678") %>

development:
  <<: *default
  database: knowledge_assistant_development

test:
  <<: *default
  database: knowledge_assistant_test

production:
  <<: *default
  database: knowledge_assistant_production
