name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint code for consistent style
        run: bundle exec rubocop -f github

  rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: knowledge_assistant_test
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: 12345678
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U admin -d knowledge_assistant_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git libpq-dev libyaml-dev pkg-config

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run tests
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGPORT: 5432
          PGUSER: admin
          PGPASSWORD: 12345678
        run: |
          bin/rails db:schema:load
          bundle exec rspec
